# Generated by Django 4.2.7 on 2024-02-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="category",
        ),
    ]
