# Generated by Django 5.0.2 on 2024-02-27 17:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('description_text', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='portfolio.jpg', upload_to='portfolio')),
                ('project_date', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 47, 14, 340819))),
                ('project_url', models.CharField(default='www.example.com', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.client')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
