# Generated by Django 4.2.7 on 2024-02-27 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="description",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="description_text",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="project_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 27, 22, 15, 55, 570517)
            ),
        ),
    ]
