# Generated by Django 4.2.7 on 2024-02-28 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_portfolio_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="project_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 28, 6, 1, 39, 417822)
            ),
        ),
    ]
