from acounts.api.V1.serializer.customeauthtoken import CustomeAuthTokenSerializer
from acounts.api.V1.serializer.customeobtainpairtoken import CustomObtainPairSerializer
from acounts.api.V1.serializer.passwordchange import PasswordChangeSerializer
from acounts.api.V1.serializer.resetPassword import ResetPasswordSerializer
from acounts.api.V1.serializer.resetPasswordEmail import ResetPasswordEmailSerializer
from acounts.api.V1.serializer.resendEmail import ResendEmailSerializer
from acounts.api.V1.serializer.registration import RegisterationSerializer