from .ChangepassView import ChangePasswordView
from .CustomeAbtainAuthToken import CustomeObtainAuthToken
from .DestroyAuthToken import DestroyAuthToken
from .IsVerified import IsVerifiedView
from .RegistrationView import RegistrationView
from .ResetpasswordEmailView import ResetPasswordEmailView
from .ResetPasswordView import ResetPasswordView
from .ResendEmailView import ResendEmailView
from .customejwtview import Customejwtview
