from acounts.api.V1.views.ChangepassView import ChangePasswordView
from acounts.api.V1.views.CustomeAbtainAuthToken import CustomeObtainAuthToken
from acounts.api.V1.views.DestroyAuthToken import DestroyAuthToken
from acounts.api.V1.views.IsVerified import IsVerifiedView
from acounts.api.V1.views.RegistrationView import RegistrationView
from acounts.api.V1.views.ResetpasswordEmailView import ResetPasswordEmailView
from acounts.api.V1.views.ResetPasswordView import ResetPasswordView
from acounts.api.V1.views.ResendEmailView import ResendEmailView
from acounts.api.V1.views.customejwtview import Customejwtview
from acounts.api.V1.views.SendSMSToken import Send_SMS